name: Blob storage Site Upload CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod site upload 
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name stgdeucecaclappresume --account-key ${{ secrets.STG_KEY }} --auth-mode key -d '$web' -s src

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cdn-deucemania-resume" --name "deucemaia" --resource-group rg-cacl-app-resume

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
